### ISSUE TITLE
Will this work with the latest 2.X versions?

### ISSUE THREAD

**Issue by planetahuevo** [BlaineMoore/sendy-webhooks#1]
Hi
Thank you for sharing this.

Is this working with the latest 2.X version and Mandrill?

**Comment by BlaineMoore** [comment]
I haven't tested it against Mandrill but it is still working fine with Critsend so I don't see any reason why it wouldn't. (No currently active mandrill accounts.)

**Comment by planetahuevo** [comment]
Hi, thank you for the fast reply, 
I am testing it right now. :+1: 
I am sending the hard_bounce/soft_bounce/spam and reject emails. 
Not sure If i should include anything else.

Waiting for mandrill for sending a forced hardbounce right now. :)

Update: 
- Rejected emails fire the bounce. 
- SoftBounce does not do anything because it waits until 3 (changed my config to two) but hard bounces works fine. 

Everything working fine. :+1:

**Comment by planetahuevo** [comment]
Everything seems to work as expected. 

Thank you again for sharing.

**Comment by BlaineMoore** [comment]
How did it work?
